In [15]:
import pandas as pd

### CSV

#### Reading Data

In [16]:
df = pd.read_csv("data/people.csv")

In [17]:
df.head()

,Index,User Id,First Name,Last Name,Age,Sex,Email,Phone,Date of birth,Job Title,City,Salary
0,1,8717bbf45cCDbEe,Shelia,Mahoney,33,Male,pwarner@example.org,857.139.8239,2014-01-27,Probation officer,Chennai,72000
1,2,3d5AD30A4cD38ed,Jo,Rivers,39,Female,fergusonkatherine@example.net,+1-950-759-8687,1931-07-26,Dancer,Mumbai,292000
2,3,810Ce0F276Badec,Sheryl,Lowery,41,Female,fhoward@example.org,(599)782-0605,2013-11-25,Copy,Kolkata,60000
3,4,BF2a889C00f0cE1,Whitney,Hooper,31,Male,zjohnston@example.com,+1-939-130-6258,2012-11-17,Counselling psychologist,Bihar,495000
4,5,9afFEafAe1CBBB9,Lindsey,Rice,33,Female,elin@example.net,(390)417-1635x3010,1923-04-15,Biomedical engineer,Mumbai,131000

##### Optional Parameters

In [ ]:
nm = ["SrNo", "Fname", "Lname", "Gender", "Email", "PhNo", "DOB", "Job"]

df1 = pd.read_csv("data/people.csv", nrows=7, header=0, names=nm)    #No column names

# nrows: reads only the first n rows
# header: defines which row is the header. If there are no headers in your csv, the first row will be taken which is wrong. Instead write header=None so pandas will automatically write header values 0->n.
# names: changes names of header values (columns). If another value is giver in header, eg. 3, all rows above 3 are not considered and the 4th row is replaced with names defined.

df1

,,,,SrNo,Fname,Lname,Gender,Email,PhNo,DOB,Job
1,8717bbf45cCDbEe,Shelia,Mahoney,33,Male,pwarner@example.org,857.139.8239,2014-01-27,Probation officer,Chennai,72000
2,3d5AD30A4cD38ed,Jo,Rivers,39,Female,fergusonkatherine@example.net,+1-950-759-8687,1931-07-26,Dancer,Mumbai,292000
3,810Ce0F276Badec,Sheryl,Lowery,41,Female,fhoward@example.org,(599)782-0605,2013-11-25,Copy,Kolkata,60000
4,BF2a889C00f0cE1,Whitney,Hooper,31,Male,zjohnston@example.com,+1-939-130-6258,2012-11-17,Counselling psychologist,Bihar,495000
5,9afFEafAe1CBBB9,Lindsey,Rice,33,Female,elin@example.net,(390)417-1635x3010,1923-04-15,Biomedical engineer,Mumbai,131000
6,aF75e6dDEBC5b66,Sherry,Caldwell,59,Male,kaitlin13@example.net,8537800927,1917-08-06,Higher education lecturer,Chennai,484000
7,efeb05c7Cc94EA3,Ernest,Hoffman,40,Male,jeffharvey@example.com,093.655.7480x7895,1984-12-22,Health visitor,Chennai,400000

#### Writing Data

In [19]:
df.to_csv("new data/data.csv", index=False)
# index=False is written because pandas auto indexes rows, which we dont want since we already have a column for index

### Excel

#### Reading Data

In [20]:
df = pd.read_excel("data/customers.xlsx")

In [21]:
df

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,dE014d010c7ab0c,Andrew,Goodman,Stewart-Flynn,Rowlandberg,Macao,846-790-4623x4715,(422)787-2331x71127,marieyates@gomez-spencer.info,2021-07-26,http://www.shea.biz/
1,2,2B54172c8b65eC3,Alvin,Lane,"Terry, Proctor and Lawrence",Bethside,Papua New Guinea,124-597-8652x05682,321.441.0588x6218,alexandra86@mccoy.com,2021-06-24,http://www.pena-cole.com/
2,3,d794Dd48988d2ac,Jenna,Harding,Bailey Group,Moniquemouth,China,(335)987-3085x3780,001-680-204-8312,justincurtis@pierce.org,2020-04-05,http://www.booth-reese.biz/
3,4,3b3Aa4aCc68f3Be,Fernando,Ford,Moss-Maxwell,Leeborough,Macao,(047)752-3122,048.779.5035x9122,adeleon@hubbard.org,2020-11-29,http://www.hebert.com/
4,5,D60df62ad2ae41E,Kara,Woods,Mccarthy-Kelley,Port Jacksonland,Nepal,+1-360-693-4419x19272,163-627-2565,jesus90@roberson.info,2022-04-22,http://merritt.com/
...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,FbcCaF483aFaFAE,Diana,Monroe,Bass-Wilson,Lake Jacksonmouth,Guatemala,+1-171-715-9766x54993,(489)413-7296x32807,cassidymercado@bonilla.com,2022-01-09,http://castro.net/
996,997,979c4D58Ae9a9cc,Jerry,Morales,Pratt-King,South Dominiquemouth,Georgia,132.253.8501x097,+1-301-292-8363x80270,gavin13@logan-downs.com,2021-08-21,https://www.braun.info/
997,998,D0DcF6a4BcefCc8,Tracie,Floyd,"Holt, Wilson and Shields",East Chloeshire,Solomon Islands,1193982387,(482)926-8966,lowehailey@oconnor.org,2020-04-22,http://www.zavala-rubio.com/
998,999,90EE9CbbDa374E9,Paul,Barnes,"Brown, Oliver and Haynes",South Shane,Finland,+1-537-466-3245x3699,791-835-9075,hodgeseddie@hardin-wells.com,2021-03-12,https://stone-randolph.info/
999,1000,51732B5b2328015,Dominic,Duran,Durham LLC,East Wendy,British Indian Ocean Territory (Chagos Archipe...,-5366,814-860-0941x057,owarner@velasquez.info,2021-12-09,http://www.cox.com/

In [28]:
df1 = pd.read_excel("data/customers.xlsx", sheet_name="Sheet2") #For excel file with multiple sheets
df1

   id    name  age  gender
0   1   shail   21    male
1   2     raj   20    male
2   3    riya   20  female
3   4    jeet   17    male
4   5  khushi   16  female

#### Writing Data

In [23]:
df.to_excel("new data/data.xlsx", index=False)
# index false is used since rows automatically get indexed, which we dont want

### JSON

#### Reading Data

In [24]:
df = pd.read_json("data/data.json")
df

,key,command,when
0,ctrl+d,editor.action.copyLinesDownAction,editorTextFocus && !editorReadonly
1,shift+alt+down,-editor.action.copyLinesDownAction,editorTextFocus && !editorReadonly
2,ctrl+d,-editor.action.addSelectionToNextFindMatch,editorFocus
3,ctrl+e,-workbench.action.quickOpen,NaN
4,ctrl+e,-workbench.action.quickOpenNavigateNextInFileP...,inFilesPicker && inQuickOpen
5,shift+alt+up,-editor.action.copyLinesUpAction,editorTextFocus && !editorReadonly
6,ctrl+e,extension.liveServer.goOnline,editorTextFocus
7,alt+l alt+o,-extension.liveServer.goOnline,editorTextFocus
8,tab,-editor.emmet.action.expandAbbreviation,config.emmet.triggerExpansionOnTab && editorTe...
9,tab,-acceptSelectedSuggestion,suggestWidgetVisible && textInputFocus
10,tab,-editor.action.inlineSuggest.commit,inlineSuggestionHasIndentationLessThanTabSize ...
11,tab,-insertBestCompletion,atEndOfWord && textInputFocus && !hasOtherSugg...
12,tab,-insertNextSuggestion,hasOtherSuggestions && textInputFocus && !inSn...
13,tab,-insertSnippet,editorTextFocus && hasSnippetCompletions && !e...
14,tab,-jumpToNextSnippetPlaceholder,editorTextFocus && hasNextTabstop && inSnippet...
15,tab,-tab,editorTextFocus && !editorReadonly && !editorT...
16,tab,tab,NaN
17,ctrl+shift+tab ctrl+shift+f5,ros.rosrun,NaN
18,ctrl+shift+right,-cursorWordEndRightSelect,textInputFocus && !accessibilityModeEnabled
19,ctrl+shift+right,editor.action.inlineSuggest.commit,inlineSuggestionVisible && tabnine.tab-overrid...
20,tab,-editor.action.inlineSuggest.commit,inlineSuggestionVisible && tabnine.tab-overrid...
21,tab,jumpToNextSnippetPlaceholder,hasNextTabstop && inSnippetMode && textInputFocus
22,tab,-jumpToNextSnippetPlaceholder,hasNextTabstop && inSnippetMode && textInputFocus
23,tab,editor.action.inlineSuggest.commit,inlineEditIsVisible && tabShouldAcceptInlineEd...
24,tab,-editor.action.inlineSuggest.commit,inlineEditIsVisible && tabShouldAcceptInlineEd...
25,alt+f,editor.action.addSelectionToNextFindMatch,NaN
26,ctrl+shift+f,workbench.action.findInFiles,NaN
27,ctrl+shift+f,-workbench.action.findInFiles,NaN
28,shift+alt+r,-revealFileInOS,!editorFocus
29,ctrl+shift+r,-workbench.view.extension.thunder-client,viewContainer.workbench.view.extension.thunder...
30,ctrl+shift+r,-workbench.action.quickOpenNavigatePreviousInR...,inQuickOpen && inRecentFilesPicker
31,ctrl+shift+r,-workbench.action.tasks.rerunForActiveTerminal,taskTerminalActive && terminalFocus
32,ctrl+shift+r ctrl+e,-editor.action.codeAction,editorTextFocus && editorLangId =~ /^(c|(cuda-...
33,ctrl+shift+r ctrl+i,-editor.action.codeAction,editorTextFocus && editorLangId =~ /^(c|(cuda-...
34,ctrl+shift+r,-rerunSearchEditorSearch,inSearchEditor
35,ctrl+shift+r,-editor.action.refactor,editorHasCodeActionsProvider && textInputFocus...
36,shift+alt+r,-java.view.package.revealFileInOS,focusedView == 'javaProjectExplorer' && java:s...
37,ctrl+shift+r,workbench.action.files.revealActiveFileInWindows,NaN
38,ctrl+k r,-workbench.action.files.revealActiveFileInWindows,NaN

#### Writing Data

In [25]:
df.to_json("new data/data.json")
# bad format for json, meaning changes

In [26]:
df1.to_json("new data/data.json", orient="records", indent=4)
# orient="records" → saves each row as a dictionary inside a list
# indent=4 → pretty formatting