In [140]:
import pandas as pd

In [141]:
df = pd.read_csv("data/people.csv")
df.head(2)
# df.drop(["Unnamed: 0","Unnamed: 0.1","Unnamed: 0.2"], axis=1, inplace=True)
# df.to_csv("data/people.csv", index=None)
display(df)

,Index,User Id,First Name,Last Name,Age,Sex,Email,Phone,Date of birth,Job Title,City,Salary
0,1,8717bbf45cCDbEe,Shelia,Mahoney,33,Male,pwarner@example.org,857.139.8239,2014-01-27,Probation officer,Chennai,72000
1,2,3d5AD30A4cD38ed,Jo,Rivers,39,Female,fergusonkatherine@example.net,+1-950-759-8687,1931-07-26,Dancer,Mumbai,292000
2,3,810Ce0F276Badec,Sheryl,Lowery,41,Female,fhoward@example.org,(599)782-0605,2013-11-25,Copy,Kolkata,60000
3,4,BF2a889C00f0cE1,Whitney,Hooper,31,Male,zjohnston@example.com,+1-939-130-6258,2012-11-17,Counselling psychologist,Bihar,495000
4,5,9afFEafAe1CBBB9,Lindsey,Rice,33,Female,elin@example.net,(390)417-1635x3010,1923-04-15,Biomedical engineer,Mumbai,131000
...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,fedF4c7Fd9e7cFa,Kurt,Bryant,57,Female,lyonsdaisy@example.net,021.775.2933,1959-01-05,Personnel officer,Mumbai,44000
996,997,ECddaFEDdEc4FAB,Donna,Barry,54,Female,dariusbryan@example.com,001-149-710-7799x721,2001-10-06,Education administrator,Mumbai,430000
997,998,2adde51d8B8979E,Cathy,Mckinney,45,Female,georgechan@example.org,+1-750-774-4128x33265,1918-05-13,Commercial/residential surveyor,Gandhinagar,330000
998,999,Fb2FE369D1E171A,Jermaine,Phelps,59,Male,wanda04@example.net,(915)292-2254,1971-08-31,Ambulance person,Mumbai,422000
999,1000,8b756f6231DDC6e,Lee,Tran,57,Female,deannablack@example.org,079.752.5424x67259,1947-01-24,"Nurse, learning disability",Rajkot,331000

### Basic GroupBy

Group by creates groups based on the value given. <br>
Then you can perform operations on those values.

In [142]:
display(df.groupby("City").size())
# How many rows per city

City
Ahmedabad       94
Banglore        93
Bihar          102
Chennai        126
Delhi          100
Gandhinagar    104
Kolkata        109
Mumbai          84
Rajkot          94
Udaipur         94
dtype: int64

In [143]:
df.groupby("City")["Age"].mean()
# Average per city

City
Ahmedabad      38.265957
Banglore       38.225806
Bihar          38.401961
Chennai        40.365079
Delhi          38.570000
Gandhinagar    39.259615
Kolkata        38.247706
Mumbai         37.750000
Rajkot         38.957447
Udaipur        39.680851
Name: Age, dtype: float64

### Group by multiple columns

In [144]:
df.groupby(["City", "Sex"])["Age"].mean()

City         Sex
Ahmedabad    Female    38.565217
             Male      37.979167
Banglore     Female    36.571429
             Male      39.588235
Bihar        Female    39.147059
             Male      38.029412
Chennai      Female    40.819672
             Male      39.938462
Delhi        Female    37.145833
             Male      39.884615
Gandhinagar  Female    40.050847
             Male      38.222222
Kolkata      Female    39.912281
             Male      36.423077
Mumbai       Female    38.697674
             Male      36.756098
Rajkot       Female    38.377358
             Male      39.707317
Udaipur      Female    40.098039
             Male      39.186047
Name: Age, dtype: float64

### Common Aggregations

<table>
<tr>
    <th>Function</th>
    <th>Meaning</th>
</tr>
<tr>
    <td>.sum()</td>
    <td>total</td>
</tr>
<tr>
    <td>.mean()</td>
    <td>average</td>
</tr>
<tr>
    <td>.count()</td>
    <td>non-null count</td>
</tr>
<tr>
    <td>.size()</td>
    <td>total rows</td>
</tr>
<tr>
    <td>.min()</td>
    <td>smallest</td>
</tr>
<tr>
    <td>.max()</td>
    <td>biggest</td>
</tr>
<tr>
    <td>.median()</td>
    <td>middle value</td>
</tr>
</table>

In [145]:
df.groupby("City")["Salary"].sum()

City
Ahmedabad      24077000
Banglore       23216000
Bihar          26839000
Chennai        32685000
Delhi          22824000
Gandhinagar    31386000
Kolkata        27271000
Mumbai         21825000
Rajkot         24197000
Udaipur        22907000
Name: Salary, dtype: int64

### Multiple aggregations at once

In [146]:
df.groupby("City")["Salary"].agg(["mean", "sum", "max", "min"])

                      mean       sum     max    min
City
Ahmedabad    256138.297872  24077000  500000  10000
Banglore     249634.408602  23216000  493000  16000
Bihar        263127.450980  26839000  499000  16000
Chennai      259404.761905  32685000  495000  11000
Delhi        228240.000000  22824000  497000  15000
Gandhinagar  301788.461538  31386000  497000  12000
Kolkata      250192.660550  27271000  499000  13000
Mumbai       259821.428571  21825000  495000  15000
Rajkot       257414.893617  24197000  493000  12000
Udaipur      243691.489362  22907000  498000  12000

### Aggregating many columns at once

In [147]:
df.groupby("City").agg({
    "Age": "mean",
    "Salary": ["min", "max"],
})

                   Age Salary
                  mean    min     max
City
Ahmedabad    38.265957  10000  500000
Banglore     38.225806  16000  493000
Bihar        38.401961  16000  499000
Chennai      40.365079  11000  495000
Delhi        38.570000  15000  497000
Gandhinagar  39.259615  12000  497000
Kolkata      38.247706  13000  499000
Mumbai       37.750000  15000  495000
Rajkot       38.957447  12000  493000
Udaipur      39.680851  12000  498000

### Reset index

In [148]:
# Creates an index for group by output
df.groupby("City")["Age"].mean().reset_index()

          City        Age
0    Ahmedabad  38.265957
1     Banglore  38.225806
2        Bihar  38.401961
3      Chennai  40.365079
4        Delhi  38.570000
5  Gandhinagar  39.259615
6      Kolkata  38.247706
7       Mumbai  37.750000
8       Rajkot  38.957447
9      Udaipur  39.680851

### Sorting group results

In [149]:
df.groupby("City")["Age"].mean().sort_values()
# Sorts by values in ascending order

City
Mumbai         37.750000
Banglore       38.225806
Kolkata        38.247706
Ahmedabad      38.265957
Bihar          38.401961
Delhi          38.570000
Rajkot         38.957447
Gandhinagar    39.259615
Udaipur        39.680851
Chennai        40.365079
Name: Age, dtype: float64

In [150]:
df.groupby("City")["Age"].mean().sort_values(ascending=False)

City
Chennai        40.365079
Udaipur        39.680851
Gandhinagar    39.259615
Rajkot         38.957447
Delhi          38.570000
Bihar          38.401961
Ahmedabad      38.265957
Kolkata        38.247706
Banglore       38.225806
Mumbai         37.750000
Name: Age, dtype: float64

### Filter groups

In [164]:
df.groupby("Salary").filter(lambda x: len(x) > 6)
# Rows belonging to Salary values that appear more than 6 times.

,Index,User Id,First Name,Last Name,Age,Sex,Email,Phone,Date of birth,Job Title,City,Salary
7,8,fb1BF3FED57E9d7,Doris,Andersen,52,Male,alicia33@example.org,4709522945,2016-12-02,Air broker,Rajkot,317000
35,36,BcdffBD402E5A23,Adrienne,Lambert,59,Male,marilyn91@example.org,157.425.5345,2019-06-16,Comptroller,Banglore,278000
97,98,e5d840eE5BB6e03,Tony,Melendez,20,Male,riveralaura@example.net,+1-618-303-1920,1924-01-22,Environmental health practitioner,Chennai,278000
98,99,DdB70783c1181Ad,Lydia,Vargas,19,Male,carly49@example.com,(656)329-5478,1948-03-06,"Accountant, chartered",Delhi,279000
111,112,120b4B8Ab9f96C0,Samantha,Harris,36,Male,wthompson@example.com,948-848-5407x6058,1965-07-17,Commercial art gallery manager,Banglore,189000
127,128,a2A4fd285DAD2b4,Autumn,Davis,19,Female,sierrabrock@example.com,(074)697-9276x0345,1929-11-25,Hydrographic surveyor,Mumbai,278000
141,142,B81eeD3F7e13A2e,Alexa,Washington,59,Female,garrettgordon@example.net,001-660-127-4590x6546,2004-12-05,"Loss adjuster, chartered",Gandhinagar,279000
156,157,49Dcb786C01C5ca,Anthony,Briggs,46,Female,marciamullins@example.org,001-299-317-0247,1951-09-15,"Biochemist, clinical",Delhi,279000
165,166,9ca2f3A7a60ea88,Mackenzie,Cantrell,51,Male,deniseromero@example.net,315.251.1410x1611,1984-04-23,"Engineer, agricultural",Banglore,189000
205,206,131570D70d0ff65,Eugene,Richmond,48,Female,xmontgomery@example.com,+1-313-656-7482,1993-11-26,"Teacher, special educational needs",Gandhinagar,317000
232,233,c905D9b34C5456C,Anita,Burnett,27,Male,chelseamendoza@example.com,001-919-880-6698x82822,1970-02-27,Neurosurgeon,Bihar,279000
245,246,BF7ad5D75edfdB5,Peter,Bruce,45,Female,max86@example.org,903-121-7928,1996-06-11,Production engineer,Banglore,189000
279,280,3aFf54f59dcFD2E,Yvette,Webster,55,Male,sonya26@example.com,795-860-8920,2006-08-14,Clothing/textile technologist,Gandhinagar,317000
289,290,ECFCF3df04cc0cF,Benjamin,Ramsey,40,Male,hbeltran@example.com,(873)889-9471,1981-12-17,Land/geomatics surveyor,Chennai,317000
292,293,c1D6Ddced4Fe3eF,Zachary,Nixon,32,Female,claudiayoung@example.com,333-779-8097x2347,1986-09-12,"Scientist, physiological",Mumbai,279000
330,331,CBff85B9A4A4Aa3,Valerie,Welch,32,Female,iortiz@example.net,001-607-800-4979x96494,1918-06-07,Brewing technologist,Udaipur,189000
401,402,faFEea3b50D6123,Kyle,Bartlett,54,Male,priscilla10@example.net,7361854341,1974-11-16,"Psychologist, sport and exercise",Bihar,278000
412,413,AAF953ce6519B3a,Holly,Manning,24,Female,vmckinney@example.net,8792929924,1915-06-06,"Radiographer, therapeutic",Ahmedabad,189000
471,472,d6DEBbCEEd1Ce8b,Linda,Patterson,47,Male,tamiblair@example.org,169.475.4021x656,1989-06-29,Actuary,Delhi,278000
514,515,6BeFa7bCaCe35bf,Marcia,Berry,52,Female,alee@example.net,281-101-3518,1960-04-20,Bookseller,Mumbai,278000
576,577,738C11c81DEeeb8,Maxwell,Greene,51,Female,maysjason@example.org,(862)324-2691x6036,2013-11-11,"Therapist, sports",Chennai,279000
613,614,59F389BC8b480eC,Katelyn,Burns,40,Male,johnswesley@example.net,+1-166-938-8350x666,1936-01-08,"Psychologist, counselling",Mumbai,317000
635,636,FbB1eCd50d46bbf,Lorraine,Miles,33,Male,wiseroberta@example.com,001-254-029-8422x633,1925-09-28,Advertising account executive,Bihar,317000
641,642,4aFFB7eC9bd16fc,Ariel,Bean,26,Female,imitchell@example.com,+1-431-536-3865x4539,1995-06-17,Chemical engineer,Gandhinagar,278000
668,669,f50FBaf6A949269,Autumn,Avila,18,Male,harringtonjames@example.net,(162)296-2950,1954-10-21,Operational researcher,Gandhinagar,279000
688,689,FF2F15A0c3e6Df6,Betty,Quinn,47,Female,cherylhuang@example.org,(261)395-6954,1910-06-04,Applications developer,Kolkata,279000
709,710,1edDB7AddBB3e9E,Richard,Rocha,57,Female,scrosby@example.com,804.289.3655x00467,1968-09-25,Food technologist,Rajkot,279000
710,711,ab2c4afC563bDc6,Kent,Flowers,24,Male,warejoanna@example.net,001-176-702-1902x2676,1984-10-05,"Teacher, adult education",Bihar,317000
912,913,7Bad31BD10CE08C,Cheryl,May,28,Female,lesliebuck@example.org,+1-112-247-3774,1982-10-19,Web designer,Bihar,189000
969,970,38128d28998a9b8,Vernon,Daugherty,48,Male,sergio60@example.com,+1-394-301-4367x02144,1929-11-18,Financial adviser,Gandhinagar,189000