In [4]:
import pandas as pd

In [5]:
df = pd.read_csv("data/people.csv")

### CONCATENATION (stacking DataFrames)

Used when you want to:
<ul>
    <li>Add more rows to a DataFrame</li>
    <li>Add more columns to a DataFrame</li>
</ul>

In [11]:
df1 = pd.DataFrame({
    "ID": [1, 2, 3, 4],
    "Name": ["Alice", "Bob", "Charlie", "David"],
    "City": ["Delhi", "Mumbai", "Chennai", "Kolkata"]
})
display(df1)

   ID     Name     City
0   1    Alice    Delhi
1   2      Bob   Mumbai
2   3  Charlie  Chennai
3   4    David  Kolkata

In [10]:
df2 = pd.DataFrame({
    "ID": [5, 6, 7],
    "Name": ["Eve", "Frank", "Grace"],
    "City": ["Mumbai", "Delhi", "Pune"]
})
display(df2)

   ID   Name    City
0   5    Eve  Mumbai
1   6  Frank   Delhi
2   7  Grace    Pune

In [15]:
# Vertical concat (add rows)
pd.concat([df1, df2], axis=0)

   ID     Name     City
0   1    Alice    Delhi
1   2      Bob   Mumbai
2   3  Charlie  Chennai
3   4    David  Kolkata
0   5      Eve   Mumbai
1   6    Frank    Delhi
2   7    Grace     Pune

In [16]:
# Horizontal concat (add columns)
pd.concat([df1, df2], axis=1)

   ID     Name     City   ID   Name    City
0   1    Alice    Delhi  5.0    Eve  Mumbai
1   2      Bob   Mumbai  6.0  Frank   Delhi
2   3  Charlie  Chennai  7.0  Grace    Pune
3   4    David  Kolkata  NaN    NaN     NaN

### MERGE (SQL-style joins)

In [21]:
df2_mod = pd.DataFrame({
    "ID": [2, 4, 7],
    "Department": ["HR", "Finance", "IT"]
})
df2_mod

   ID Department
0   2         HR
1   4    Finance
2   7         IT

##### INNER JOIN

In [ ]:
inner_join = pd.merge(df1, df2_mod, on="ID", how="inner")   #takes common of both
inner_join

   ID   Name     City Department
0   2    Bob   Mumbai         HR
1   4  David  Kolkata    Finance

##### LEFT JOIN

In [ ]:
left_join = pd.merge(df1, df2_mod, on="ID", how="left") #takes all the values of the left one (df1)
# left_join = pd.merge(df2_mod, df1, on="ID", how="left") #takes all the values of the left one (df2_mod)
left_join

   ID Department   Name     City
0   2         HR    Bob   Mumbai
1   4    Finance  David  Kolkata
2   7         IT    NaN      NaN

##### RIGHT JOIN

In [25]:
right_join = pd.merge(df1, df2_mod, on="ID", how="right")   #takes all the values of the right one(df2_mod)
right_join

   ID   Name     City Department
0   2    Bob   Mumbai         HR
1   4  David  Kolkata    Finance
2   7    NaN      NaN         IT

##### FULL OUTER JOIN

In [ ]:
outer_join = pd.merge(df1, df2_mod, on="ID", how="outer")   #takes all values
outer_join

   ID     Name     City Department
0   1    Alice    Delhi        NaN
1   2      Bob   Mumbai         HR
2   3  Charlie  Chennai        NaN
3   4    David  Kolkata    Finance
4   7      NaN      NaN         IT

### JOIN (index-based merge)

In [28]:
df1_idx = df1.set_index("ID")
df2_idx = df2_mod.set_index("ID")

df1_idx.join(df2_idx, how="left")

       Name     City Department
ID
1     Alice    Delhi        NaN
2       Bob   Mumbai         HR
3   Charlie  Chennai        NaN
4     David  Kolkata    Finance